services:
  satisfactory-server:
    image: wolveix/satisfactory-server:latest
    container_name: satisfactory-server
    hostname: satisfactory-server
    restart: unless-stopped
    ports:
      - "7777:7777/udp"
      - "7777:7777/tcp"
      - "15000:15000/udp"
      - "15777:15777/udp"
    volumes:
      - ./config:/config
    environment:
      - TIMEOUT=300 # Forces the script to set "ConnectionTimeout=300.0"
      - NETWORKQUALITY=1 # Keep this at Medium for stability over VPN
      - SERVER_IP=100.120.36.88 # Tailscale IP to avoid docker internal IP issues
      - MAXPLAYERS=8
      - PUID=1000
      - PGID=1000
      - ROOTLESS=false
      - STEAMBETA=false
      - AUTOPAUSE=true
      - AUTOSAVENUM=5
      - AUTOSAVEINTERVAL=300
      - CRASHREPORT=true
      - DEBUG=false
      - SERVERGAMEPORT=7777
      - SERVERBEACONPORT=15000
      - SERVERQUERYPORT=15777
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
